# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
#' 
NULL

MSFRVI_cpp <- function(YList, ZList, rank_use, invLambda_int, A_int, BList_int, bbeta_int, MuList_f_int, SList_f_int, MuList_h_int, SList_h_int, ic, epsELBO, maxIter, verbose, loop_ic = FALSE) {
    .Call(`_MultiCOAP_MSFRVI_cpp`, YList, ZList, rank_use, invLambda_int, A_int, BList_int, bbeta_int, MuList_f_int, SList_f_int, MuList_h_int, SList_h_int, ic, epsELBO, maxIter, verbose, loop_ic)
}

#' @keywords internal
#' @noRd
#' 
NULL

MuCOAP_cpp <- function(XcList, aList, ZList, rank_use, MuList_y_int, SList_y_int, invLambda_int, A_int, BList_int, bbeta_int, MuList_f_int, SList_f_int, MuList_h_int, SList_h_int, ic, epsELBO, maxIter, verbose, loop_ic = FALSE) {
    .Call(`_MultiCOAP_MuCOAP_cpp`, XcList, aList, ZList, rank_use, MuList_y_int, SList_y_int, invLambda_int, A_int, BList_int, bbeta_int, MuList_f_int, SList_f_int, MuList_h_int, SList_h_int, ic, epsELBO, maxIter, verbose, loop_ic)
}

